### ISSUE TITLE
CPU abstraction

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/infoware#1]
We need a way of finding out all relevant CPU information. This issue will be for what should theoretically be in there.

- [x] Physical Core Count (e.g., physical cores vs. 'Hyper-Threaded' cores)
- [x] Hardware Concurrency count (e.g., physical cores vs. 'Hyper-Threaded' cores)
- [x] Current Clock Speed
- [ ] Min/Max Clock Speeds
- [x] Model Name
- [x] Top-Level Vendor Enumeration? (Intel, AMD, Qualcomm...? Just leave it a string, is probably a better idea)
- [x] Endianness (Generally Little, except or PowerPC-based archs (Big Endian, see XBox 360))
- [x] Instruction Set
- [x] Architecture
- [x] Caches

**Comment by nabijaczleweli** [comment]
I'll get on "Clock Speed" tomorrow

**Comment by TheCatPlusPlus** [comment]
Capabilities described by CPUID are much more interesting than almost all of that :v. Also NUMA topology is fairly important.

**Comment by ThePhD** [comment]
Thanks to @Mysticial we don't have to go through the pain of figuring out CPUID stuff: http://stackoverflow.com/a/7495023/5280922

**Comment by ThePhD** [comment]
After extensive research (and reading through some of Mysticials old conversations on the topic), Min/Max clockspeed (and even clockspeed itself) is a tad unreliable to get (even with the rdtsc intrinsic). That's something unfortunately you'd have to know on a per-CPU basis, and with knowledge of the hardware. CPU-Z isn't sharing, so we'll just leave that one alone.
