### ISSUE TITLE
Compile on linux

### ISSUE THREAD

**Issue by EndErr** [ThePhD/infoware#10]
How to use that library on a linux platform?

**Comment by nabijaczleweli** [comment]
You should be able to do `make`, then link to `libinfoware.a` and include files from the  `include/` to use the library, there are no required special steps to it on Linux. (There are *optional* ones, however, as forthlaid in the Configuration sexion in README.)

The only problem I encountered on my Linux machine just now when trying to build the library was the missing `cpuid.h` header; that is, however, a common issue, and you should be able to copy `/usr/lib/gcc/{your-dist}/{some-version}/include/cpuid.h` into `/usr/include/` to alleviate it.

**Comment by nabijaczleweli** [comment]
Guessing you managed to build, then, @EndErr?
