### ISSUE TITLE
segfault on example "cpu"

### ISSUE THREAD

**Issue by Nitoref** [ThePhD/infoware#11]
Quantities:
        Logical CPUs : 8
        Physical CPUs: 0
        CPU packages : 0

      Caches:
        L1:
          Size         : 0B
          Line size    : 0B
          Associativity: 0
          Type         : Unified
        L2:
          Size         : 0B
          Line size    : 0B
          Associativity: 0
          Type         : Unified
        L3:
          Size         : 0B
          Line size    : 0B
          Associativity: 0
          Type         : Unified

      Architecture: x64
      Frequency: 0 Hz
      Endianness: Little-Endian
    Segmentation fault: 11

Done on a 2015 15" MacbookPro with   2.2 GHz Core i7 4770HQ cpu.

**Comment by nabijaczleweli** [comment]
Thanks for reporting, could you check if the example still crashes with the freshest commit from the `bugfix/cpuinfo_value_segfault` branch?

As for the efficacy of the test, I'm getting a feeling Macs need treatment different from generic non-Windows for this, unfortunately

**Comment by Nitoref** [comment]
It's all good with your fix !

**Comment by nabijaczleweli** [comment]
Nice. Pushing patch to `master`, then.

I'll see what I can do about acquiring CPU data on Macs, but neither of us has a test machine, so that might be tricky :v

**Comment by Nitoref** [comment]
I might not be able to work on your code, but if you need me to do some testing just let me know.
