### ISSUE TITLE
Displays on Darwin

### ISSUE THREAD

**Issue by nabijaczleweli** [ThePhD/infoware#17]
I'm gonna venture that that'd require ObjC, but let's hope

**Comment by nabijaczleweli** [comment]
[This](https://stackoverflow.com/questions/25771216/get-display-monitor-names-in-c-mac) and all the other answers say it's only ObjC so

**Comment by arthurbiancarelli** [comment]
Hello, actually the Carbon APIs and especially the graphic part (Quartz) are C-based APIs from what I understood (see the wikipedia page [here](https://en.wikipedia.org/wiki/Carbon_(API))). I successfully tried to used them in the project, as you can see [here](https://github.com/arthurbiancarelli/infoware/commits/ab/display) and particularly this [commit](https://github.com/arthurbiancarelli/infoware/commit/b087e7f5153c458a8df6ba960cef26ed61de2995).  From what I understood these APIs are becoming deprecated in favour of the new Cocoa ones, but it's still unclear to me if the new ones are Obj-c only or not.  In the worst case scenario, it's seems possible to create bindings Obj-c/ C

**Comment by nabijaczleweli** [comment]
I merged (well, sequentially cherry-picked, but whatever) your branch into `master` yielding the following rangespec: https://github.com/ThePhD/infoware/compare/d24cbcec776ec873fb0bc0f45ca711e6ed79ba7f...237a8cd047d24f91c6a0fc5ed8e476d3f1cd9e4c. Thanks for your work on this!

**Comment by nabijaczleweli** [comment]
Released in [`v0.2.0`](https://github.com/ThePhD/infoware/releases/tag/v0.2.0)! Thanks again for your contribution!

**Comment by arthurbiancarelli** [comment]
Great !
