### ISSUE TITLE
CPU Frequency on Windows is bogus

### ISSUE THREAD

**Issue by melak47** [ThePhD/infoware#18]
The windows implementation of `iware::cpu::frequency` does basically `QueryPerformanceFrequency() * 1000` -- which returns completely bogus values. 
On my machine, `QueryPerformanceFrequency` returns e.g. 10 MHz, so this reports 10 GHz...

Finding accurate values may be hard, but would it be preferable to return a guesstimate from `HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0\~MHz` (e.g. 3696 on my machine)?

**Comment by nabijaczleweli** [comment]
Interesting, it's always returned the correct value for me. Alas!

**Comment by nabijaczleweli** [comment]
Check the `fix/18-winfreq` branch, if you'd?

**Comment by melak47** [comment]
Works on my machine:tm: 👍

**Comment by nabijaczleweli** [comment]
Landed in `master`
