### ISSUE TITLE
Enumerate available display configurations on Darwin

### ISSUE THREAD

**Issue by nabijaczleweli** [ThePhD/infoware#22]
Couldn't find any relevant funxion in the [Quartz/Carbon API](https://developer.apple.com/documentation/coregraphics/quartz_display_services?language=objc) but it's late and I'm tired so

**Comment by nabijaczleweli** [comment]
https://developer.apple.com/documentation/coregraphics/1455537-cgdisplaycopyalldisplaymodes?language=objc

**Comment by nabijaczleweli** [comment]
hey @arthurbiancarelli, mind running the `system` example on [current `master](https://github.com/ThePhD/infoware/commit/7881a0ffa363251f312cfbbf15d11f939af3b374)?

**Comment by arthurbiancarelli** [comment]
Hey, I just run the example, here the report: https://pastebin.com/raVHhiHp

**Comment by nabijaczleweli** [comment]
Thanks!
This seems pretty in line with what I'd expect, I guess? Now, if only Quartz supported refresh rates sensibly…

**Comment by nabijaczleweli** [comment]
Released in [`v0.2.1`](https://github.com/ThePhD/infoware/releases/tag/v0.2.1)

**Comment by arthurbiancarelli** [comment]
Yes, everything seems coherent even if it's too bad for the refresh rate.. I'll try with an external display 
I'll do a bit more research but it doesn't seem easy to get this value on Mac machines
