### ISSUE TITLE
System abstraction

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/infoware#3]
We need a way of finding out more overarching system information not directly related to the internal hardware. May include:
- [x] OS Vendor / Information (Ubuntu, Windows 10, etc.) (Probably going to need a versioning structure for these things too)
- [x] Kernel Information (Linux, Vista, whatever the fuck is inside Mac OSX)
- [x] Monitor/Display Count (kind've stretch, but would be nice, can also include extra information like 'High DPI' and what not)
- [x] Memory (size in bytes)

Fancy:
- [x] # of mice
- [x] # of keyboards

**Comment by nabijaczleweli** [comment]
lol fan count, how do you detect that

**Comment by nabijaczleweli** [comment]
From a quick skim over WinAPI, there doesn't seem to exist a way of getting mouse amount.

**Comment by ThePhD** [comment]
You'd need RawInput to figure that out. Which requires a Window Handle to work with. So we might have to make an invisible window in the background.

**Comment by nabijaczleweli** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms645598(v=vs.85).aspx

**Comment by TheCatPlusPlus** [comment]
All device enumeration on Windows is done through [SetupDi](https://msdn.microsoft.com/en-us/library/windows/hardware/ff541299(v=vs.85).aspx). RawInput gives you a very narrow view into that and you'll need to extract device IDs and use SetupAPI to get anything interesting anyway.

**Comment by ThePhD** [comment]
Do we really need Fan Count and things like that? I would imagine just for dumping out information for benchmarks or tests, we've already covered all the bases (and fans aren't a thing aside from physical machines; same with mice/keyboard stuff...?)

**Comment by ThePhD** [comment]
Don't need fan counts and other stuff like that.
