### ISSUE TITLE
C++ package management?

### ISSUE THREAD

**Issue by SamuelMarks** [ThePhD/infoware#41]
I've used vcpkg and Conan before, but I'm keen to try Hunter or the decentralised Buckaroo https://hackingcpp.com/cpp/tools/package_managers.html

Happy to contribute, just want to know what you want

**Comment by ThePhD** [comment]
Are you asking if we will put these in package managers,

or if we are going to solve the package manager problem...? It seems like the first one, but the phrasing and the issue title sort of makes it seem like you want us to do the second...!

If it's the first, I've already started on a vcpkg but I have no idea what I'm doing so writing the CONTROL and portfile and etc. is a bit slow-going. If you want to start on Conan, Hunter, Buckaroo integration, let me know.

**Comment by SamuelMarks** [comment]
Oh, you're already working on implementing support for one of them?

Happy to help out, commit your WiP and I'll see what I can do =)

**Comment by ThePhD** [comment]
@SamuelMarks I've got a bunch of work to do over the next few days, so I'm not sure I can get the vcpkg stuff in a steady state to commit.

You can start on Conan or Hunter support; I know I will definitely take care of vcpkg. Just so we don't try to duplicate work here. :D

**Comment by nabijaczleweli** [comment]
NB: package management in C++ is a trash-fire and uploading to fifteen
archive is fun until it isn't; consider one or two package managers at
*most*, preferably ones that are a thin shim on CMake.

**Comment by ThePhD** [comment]
I got the distribution for vcpkg down, I think...

Just need to make a pull to the vcpkg repo.

**Comment by SamuelMarks** [comment]
Closed https://github.com/microsoft/vcpkg/pull/11410

[close this issue when that is merged]

**Comment by ThePhD** [comment]
Bitchin', it's in: https://github.com/microsoft/vcpkg/pull/11410

**Comment by SamuelMarks** [comment]
🎉
