### ISSUE TITLE
Zero values for non-primary displays on Windows

### ISSUE THREAD

**Issue by Asmodai** [ThePhD/infoware#44]
My secondary display was showing a resolution of `0x1080` rather than `1920x1080`, as it's to the left of the primary display (thus has a `left` value of `-1920`, and a `right` value of `0`).

The fix is to simply compute the width and height of the display's rect and run it past `abs` to be ultra pedantic.

I have not tested this fix on all possible display configurations. 

PR: #43

**Comment by nabijaczleweli** [comment]
Released in [`v0.5.4`](https://github.com/ThePhD/infoware/releases/tag/v0.5.4)
