### ISSUE TITLE
vcpkg install infoware doesn't get the detail includes

### ISSUE THREAD

**Issue by Dreamykass** [ThePhD/infoware#45]
Got infoware through vcpkg, installed fine. Added to my cmake lists, also ok. Tried to include - compile time errors: `Cannot open include file: 'infoware/detail/linkage.hpp': No such file or directory (...)`.

Looked into `vcpkg/packages/infoware_x64-windows/include/infoware`, and yeah, there's no `detail` folder in there.

**Comment by nabijaczleweli** [comment]
Thanks for the report, fix released in [`v0.5.5`](https://github.com/ThePhD/infoware/releases/tag/v0.5.5)

**Comment by Dreamykass** [comment]
Thanks for the fix, and for the work on the lib and stuff!

**Comment by Dreamykass** [comment]
Wait, it looks like there's no `infoware.dll` I think?

vcpkg installs fine, cmake builds fine, the project builds fine, but there's no output when ran from the terminal, and when ran by clicking the exe there's a system dialog box "inforware.dll not found".

Earlier (as in like half an hour ago) I did `vcpkg upgrade infoware --no-dry-run`... and it somehow deleted `vcpkg/packages/infoware...`? So I had to remove it and install again, and the folder came back. But now there's no `infoware.dll` apparently.

**Comment by Dreamykass** [comment]
Sorry for the spam I guess, but after doing some digging, it looks like the debug configuration is looking for `infoware.dll`, while it should be `infowared.dll` (which is in `vcpkg\installed\x64-windows\debug\bin`). The release config works fine.

**Comment by ThePhD** [comment]
That's configured in the CMake so vcpkg should've picked it up automatically...
