### ISSUE TITLE
unresolved external symbol const iware::version

### ISSUE THREAD

**Issue by MohammadKanan** [ThePhD/infoware#46]
Compiled with Visual Studio 2017 , when I compile whole project with examples .. everything is ok.
When compile shared library (with DLL) , and include in my project .. get this error : `unresolved external symbol const iware::version`
All other interfaces are working fine.

**Comment by nabijaczleweli** [comment]
What's the export list on the DLL?

**Comment by MohammadKanan** [comment]
Sorry for the confusion, I actually was trying to compile the shared library .. got confused with a cmake configuration entry something called "public" which sets shared ... I misunderstood that part ..  and thought its already compiling shared  library and DLL; just compiled normally with cmake  BUILD_SHARED_LIBS ..
Sorry for inconvenience. Thanks.

**Comment by ThePhD** [comment]
That's fine, glad you ended up getting it!
