### ISSUE TITLE
Linux OpenGL GPU detection didn't detected anything, OpenCL works

### ISSUE THREAD

**Issue by Zaraka** [ThePhD/infoware#68]
If compiled with OpenGL support and example, the `infoware_gpu_example` returns this
```
Infoware version 0.6.0

  Properties:
    No detection methods enabled
```

When compile with OpenCL, the GPU is correctly detected:
```
Infoware version 0.6.0

  Properties:
    Device #1:
      Vendor       : AMD
      Name         : gfx1031
      RAM size     : 12868124672B
      Cache size   : 16384B
      Max frequency: 2880000000Hz
```

There should be at least a mention in the ReadMe that OpenCL is preferred because I noticed this issue after months of use, when I found out all my Linux devices didn't report their GPU info.

**Comment by nabijaczleweli** [comment]
Yep, OpenGL detexion is currently unimplemented the same as nothing at all – compare https://github.com/ThePhD/infoware/blob/575b4dbd3e7fe5044af2ca28ae7a6ebb168086d0/src/gpu/OpenGL.cpp with https://github.com/ThePhD/infoware/blob/575b4dbd3e7fe5044af2ca28ae7a6ebb168086d0/src/gpu/blank_all.cpp.

**Comment by Zaraka** [comment]
I see, this is unfortunate, no promises but I can try to deliver EGL implementation in the future

**Comment by nabijaczleweli** [comment]
Closed by https://github.com/ThePhD/infoware/pull/73
