### ISSUE TITLE
The GPU 1050 Ti name is GP107?

### ISSUE THREAD

**Issue by webees** [ThePhD/infoware#7]
See the figure below:
![_20180422160145](https://user-images.githubusercontent.com/5155291/39092703-8fc1a45c-4646-11e8-9ec8-ea3320f32622.png)

ther software displays:
![_20180422160202](https://user-images.githubusercontent.com/5155291/39092717-b63d2502-4646-11e8-9976-b73d07516dda.png)

I hope to be updated. Thank you very much.

Maybe I misunderstood the description. The above two pictures are other computers. The picture below is my computer.

My notebook display is correct. Why?
![_20180422160628](https://user-images.githubusercontent.com/5155291/39092736-279e6a1c-4647-11e8-8ef0-8dd41ca65c7f.png)

**Comment by nabijaczleweli** [comment]
Which GPU detexion are you using?

**Comment by webees** [comment]
thank @nabijaczleweli https://github.com/CherryPill/system_info/

**Comment by nabijaczleweli** [comment]
By the detection system you're using I meant the one in `infoware`: are you using D3D or OpenCL? Does it work with the other one?

And thanks for the link, I might just steal `system_info`'s detector.

**Comment by webees** [comment]
Sorry, I don't know if it's d3d or opencl. I used the demo you provided to make a gpu.exe that just runs on a different computer and produces different results. GP107 is displayed on the win7 system.

**Comment by webees** [comment]
Win7 system (computer number 1):
Infoware display: GP107
System_info Display: NVIDIA GeForge GTX1050 Ti 4095 MB

Win10 system (computer number 2):
Infoware show: NVIDIA GeForge GTX1050


System_info seems to get data through WMI.

**Comment by nabijaczleweli** [comment]
Well, it seems that I've run into a severe problem in that I can't get `ld` to link to COM properly. maybe someone (PhD?) with a ~~worse~~ better toolchain will be able to fix the linking errors to `CLSID_WbemAdministrativeLocator` and `IID_IUnknown`. For now, I've pushed my working diff to the `feature/WMI-GPU` branch.

**Comment by nabijaczleweli** [comment]
Anyway, the 1050Ti uses the GP107 processor:
https://www.techpowerup.com/gpu-specs/nvidia-gp107.g801
https://www.techpowerup.com/gpu-specs/geforce-gtx-1050-ti.c2885

So the output does seem correct :v
