### ISSUE TITLE
Hey, I don't know why, Pubg game report virus.

### ISSUE THREAD

**Issue by webees** [ThePhD/infoware#9]
Win7 operating system.

When the graphics card information is obtained, Virus, file that is wrong, cannot be ignored. When the relevant code is removed, it will be normal.

**Comment by nabijaczleweli** [comment]
Terribly sorry mate, what? What's "report poison"? Which code is relevant?

**Comment by webees** [comment]
like this：
![_20180819005141](https://user-images.githubusercontent.com/5155291/44301482-3c565b80-a34a-11e8-8ebd-ff7a0196b7f6.png)

**Comment by webees** [comment]
Error code example

```
	void gpu() {
		const auto device_properties = iware::gpu::device_properties();
		if (!device_properties.empty()) {
			G_PC["gpu_0_name"] = device_properties[0].name;
			G_PC["gpu_0_ram"] = device_properties[0].memory_size;
			G_PC["gpu_1_name"] = device_properties[1].name;
			G_PC["gpu_1_ram"] = device_properties[1].memory_size;
		}
		const auto displays = iware::system::displays();
		if (!displays.empty()) {
			G_PC["gpu_wh"] = to_string(displays[0].width) + "x" + to_string(displays[0].height);
		}
	}
```

**Comment by nabijaczleweli** [comment]
Looks like either `dxtheme.dll` (that's the crossed out DLL, right?) got infected, or the launcher(?)/AV considers device enumeration a virus/attack (which it very well could be, but not in this case). I can't reproduce this, though, so dunno what to do with this :v

**Comment by webees** [comment]
No, the picture was found on the Internet. The crossed out dll is infoware.dll.

**Comment by nabijaczleweli** [comment]
So what you're saying is you're reporting bullshit. Provide *all, genuine, relevant* data or stop entirely.
